server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 180000  # 3 minutes (in milliseconds)
    threads:
      max: 200

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      thread-name-prefix: EdTradePlanner-
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=1h
  jackson:
    default-property-inclusion: "NON_NULL"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    com.edtradeplanner: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
